version: 0.2

env:
  variables:
    ANSIBLE_HOST_KEY_CHECKING: false
    SITE_KEY: example.com # TODO: Change me!

phases:
  install:
    commands:
      # Start SSH agent
      - eval `ssh-agent -s`

  pre_build:
    commands:
      # Add private key to SSH agent
      - echo "$PRIVATE_KEY" > $HOME/.ssh/id_rsa
      - chmod 600 $HOME/.ssh/id_rsa*
      - expect-ssh-add.sh id_rsa $PRIVATE_KEY_PASSPHASE

  # Deploy
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/trellis && ansible-playbook deploy.yml -e env=$SITE_ENV -e site=$SITE_KEY -vvvv

cache:
  paths:
    - /usr/local/share/.cache/yarn/v1/**/*
